import Head from 'next/head'
import {Image, Stack, Title, Text, useMantineTheme} from '@mantine/core';
import {useSession} from "next-auth/react";

export default function Home() {
    const theme = useMantineTheme();
    const { data: session, status } = useSession();

    return (
        <>
            <Head>
                <title>Index</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {status === 'authenticated' ? (
                <Stack>
                    <Title order={2}>Hi {session.user.email}, thank you for using Beat Piper</Title>
                </Stack>
            ) : (
                <Stack align="center">
                    <Image src="/logo.png" alt="Logo" height={250} fit="contain"/>
                    <Title order={1}>Beat Piper</Title>
                    <Text color={theme.colors.gray[5]}>Play your Spotify collection in Beat Saber now!</Text>
                </Stack>
            )}
        </>
    )
}
